/*
 * ADC_Config.h
 *
 * Created: 6/29/2022 6:16:03 PM
 *  Author: pc
 */ 


#ifndef ADC_CONFIG_H_
#define ADC_CONFIG_H_
#include "ADC_Types.h"
/*
*configure the voltage reference
*Range:
*   ADC_VOLTAGE_REF__AREF		
    ADC_VOLTAGE_REF__AVCC		
	ADC_VOLTAGE_REF__2_56v
	*/
#define ADC_VOLTAGE_REF_SELECTOR_msk        ADC_VOLTAGE_REF__AVCC	



/*CONFIGURE the ADC MODE
	Range:
	 ADC_MODE_AUTO_TRIGGER			
	 ADC_MODE_SINGLE_CONVERSION	
	 */
#define ADC_MODE_SELECTOR					ADC_MODE_AUTO_TRIGGER	

/*Configure the ADC adjustment
	Range:
	ADC_RIGHT_ADJUSTMENT
	ADC_LEFT_ADJUSTMENT
	*/
#define ADC_ADJUSTMENT_SELCTOR				ADC_RIGHT_ADJUSTMENT

/*configure ADC PRESCALER
	Range:	
	ADC_PRESCALAER_2_msk		
	ADC_PRESCALAER_4_msk		
	ADC_PRESCALAER_8_msk		
	ADC_PRESCALAER_16_msk		
	ADC_PRESCALAER_32_msk		
	ADC_PRESCALAER_64_msk		
	ADC_PRESCALAER_128_msk		
*/
#define ADC_PRESCALER_SELECTOR				ADC_PRESCALAER_128_msk	

/*CONFIGURE ADC AUTO TRIGGER SELECTOR
Range:
  ADC_AUTO_TRIG_SRC_CLR_msk					 
  ADC_AUTO_TRIG_SRC_FREE_RUNNING_msk			 
  ADC_AUTO_TRIG_SRC_FREE_ANALOG_COMP_msk      
  ADC_AUTO_TRIG_SRC_FREE_EXIT0_msk
  ADC_AUTO_TRIG_SRC_TIMER0_COMP_msk			 
  ADC_AUTO_TRIG_SRC_TIMER0_OVF_msk			
  ADC_AUTO_TRIG_SRC_TIMER1_COMP_msk			 
  ADC_AUTO_TRIG_SRC_TIMER1_OVF_msk			 
*/
#define ADC_AUTO_TRIGGER_SRCE_SELECTOR		 ADC_AUTO_TRIG_SRC_FREE_RUNNING_msk

#endif /* ADC_CONFIG_H_ */